services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${APP_CONFIG__DB__DATABASE}
      MYSQL_USER: ${APP_CONFIG__DB__USER}
      MYSQL_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${APP_CONFIG__RABBIT__USER}
      RABBITMQ_DEFAULT_PASS: ${APP_CONFIG__RABBIT__PASSWORD}
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    command:
      sh -c "
      poetry run alembic upgrade head && \
      poetry run uvicorn main:main_app --host 0.0.0.0 --port 8000 --reload
      "
    depends_on:
      - db
      - dramatiq
    ports:
      - "8000:8000"


  dramatiq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dramatiq_app
    command: >
      sh -c "
      poetry run dramatiq tasks.worker
      "
    depends_on:
      - rabbitmq
      - redis


volumes:
  db_data: